apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl-client
  template:
    metadata:
      labels:
        app: curl-client
    spec:
      containers:
        - name: curl-client
          image: curlimages/curl:latest
          command: ["/bin/sh"]
          args: ["-c", "while true; do sleep 10; done"]
